JaMR94/JaMR94.github.io

- package-lock.json
- package.json
Se termino de crear el Footer, se eliminó la rama anterior y se creó una nueva por problemas del Github
> Creación de Footer

- src/components/componentsDetaillProducts/butomSelectProducts.jsx
- src/components/componentsDetaillProducts/descriptionProducts.jsx
- src/components/componentsDetaillProducts/headerProducts.jsx
- src/components/componentsDetaillProducts/imgProducts.jsx
- src/components/componentsDetaillProducts/selectDescriptionProducts.jsx
- src/pages/DetaillProducts.js
- src/styles/butomSelectProducts.module.css
separando el css del global a butomSelectProducts.module.css e importándolo a cada componente según lo necesite en el issues lo voy a poner mas explicado por si alguien lo necesita 
ojo hay que comentar una parte del css gloval no lo subi comentado porque hay estilos de otros proyectos
> agregando mi css

- src/components/Checkout/pagos_form.jsx
- src/components/Checkout/pagostitle.jsx
- src/components/Contact_us/contact_form.jsx
- src/components/Contact_us/titulo_contact.jsx
- src/components/Layouts/Layout.jsx
- src/pages/Contact_us.js
- src/pages/DetaillProducts.js
- src/pages/RegisterPage.js
- src/pages/_app.js
- src/pages/aboutpage.js
- src/pages/checkout.js
- src/pages/index.js
- src/styles/ContactUs.css
- src/styles/inicio.css
- src/styles/pagos.css
se modifico el layout
se creo la carpeta layout
se creo la pagina checkout/ versión temprana/ responsivo se agrego el contact us/ versión temprana/ semi responsivo
> modificaciones

- src/components/Carrito.jsx
- src/pages/DetaillProducts.js
- src/styles/globals.css
se hiso unos cambios en detail products porque se repetía el footer 
se creo el componente de carrito para posterior mente agregarlo a el layaut y así funcione en todos lados 
como hacerlo ???
importar Carrito 
al botón donde lo quieres poner le agregas los siguientes parámetros 
data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions"
> parche de los productos y el componente carrito

- src/components/Layouts/Layout.jsx
- src/components/navbar.jsx
se importo el componente carrito en el layout
y se agregaron características al botón del carrito
> carrito terminado

- src/components/Layouts/Layout.jsx
- src/components/navbar.jsx
- src/styles/SearchBar.module.css
se hizo breves cambios para integrar la barra de busqueda en el navbar
> se organizo la barra de busqueda

- src/components/aboutlifestory.jsx
- src/components/aboutourphilosophy.jsx
- src/components/aboutustitulo.jsx
- src/styles/About.css
Se corrigio ciertos errores que se generaron durante los commit
> Correccion de About Us

- src/components/footer.jsx
- src/styles/footer.module.css
- src/styles/globals.css
- src/styles/monthly.module.css
Se acomodo el responsive del monthly/footer. Si no se llega a visualizar, avisen...
> Ajuste del Responsive

- src/components/Navpage.jsx
- src/pages/Navpage.js
- src/styles/About.css
> Creacion de nav

- src/styles/globals.css
- src/styles/monthly.module.css
Se cambio algunas cosas dentro del css de montlhy, salu3!
> Cambios de secc monthly

- package-lock.json
- package.json
- src/components/Layouts/Layout2.jsx
- src/components/LoginPage.jsx
- src/components/RegisterPage.jsx
- src/pages/LoginPage.js
- src/pages/RegisterPage.js
- src/styles/Login&Register.css
Cambios en css + responsive y rceación de layout2
> Cambios CSS Y Layout

- src/components/Products/cardsection.jsx
- src/components/componentsDetaillProducts/butomSelectProducts.jsx
- src/components/componentsDetaillProducts/descriptionProducts.jsx
- src/pages/DetaillProducts/[id].js
se hiso el redireccionamiento de los productos a los detalles de cada producto según su id
> el redireccionamiento a los diferentes detalles de los productos

- src/components/Products/cardsection.jsx
- src/pages/DetaillProducts/[id].js
- src/pages/Productos.js
> cambios del profesor @abraham1669

- src/components/Navpage.jsx
- src/styles/About.css
Se cambiaron las etiquetas "a" por Link
> Finalizacion de Navbar

- src/components/Contact_us/contact_form.jsx
se agregó algunas propiedades en contact form
se instalo emailjs, para poder trabajar con el envio de correo
> contact us

- src/pages/DetaillProducts.js
- src/pages/DetaillProducts/[id].js
- src/pages/Productos.js
- src/pages/index.js
se agregaron trycatch error para atrapar el error y se configuro para que se recargue la pagina para que el usuario no lo tenga que hacer.
archivos a los cuales se les añadieron los trycatch: 
1. DetailProducts.js (src>pages>DetailProducts.js)
2. [id].js (src>pages>Detailproducts>[id],js)
3. index.js(src>pages>index.js)
4. Productos.js(src>pages>Productos.js)
> solución al error runtime error

- src/styles/About.css
> Responsive About Us

- src/components/about_us/aboutustitulo.jsx
Actualización del texto que contenia Lorem ipsum.
> Actualización del texto_aboutustitulo

- src/components/about_us/aboutourphilosophy.jsx
Actualización del texto que contenia Lorem ipsum.
> Actualización del texto_Aboutourphilosophy

- package-lock.json
- package.json
- src/components/Carrito.jsx
- src/styles/Carrito.module.css
Se hizo que el carrito mostrara lo que contiene la api https://ecommerce-unid.000webhostapp.com/order_detail
> Carrito modificaciones estrella
